development:
   adapter: postgresql
   encoding: unicode
   database: my_app_production
   pool: 5
   username: postgres
   password: wahwah

test: &test
   adapter: postgresql
   encoding: unicode
   database: my_app_test
   pool: 5
   username: postgres
   password: wahwah

production:
   adapter: postgresql
   encoding: unicode
   database: d39o800311h62b
   pool: 5
   username: db_user
   password: db_pass
cucumber:
  <<: *test